### PR TITLE
Adopt ruff formatter and linter

### PR DESCRIPTION
**Pull request by xshapira**
Replace flake8 and black with ruff.

### CODE REVIEW

**Comment by jonathan-s** [comment]
Thanks for the PR. It appears some checks are failing.

**Comment by xshapira** [comment]
> This is where it seems to fail in the pipeline. Is it not failing locally?
> 
> tests/test_fields.py::test_enum_choices FAILED

It's failing locally for me, but I can't figure out why. After looking into it, I suspect two validation errors happen because of how the `preferred_sport` and `preferred_musician` fields are defined in the `PreferenceSchema`.

The fields are defined as enums, yet the values `""` (empty string) and `None` aren't part of the enum choices. So when the tests try to validate instances with those values, it's going to throw an error. Does that make sense?

**Comment by jonathan-s** [comment]
I'm guessing that it is related to a newer version of pydantic. Does the problem go away if you use pydantic==2.6.2, if that's the cause at least it pins down where the problem comes from which makes it easier to solve :).

**Comment by xshapira** [comment]
> I'm guessing that it is related to a newer version of pydantic. Does the problem go away if you use pydantic==2.6.2, if that's the cause at least it pins down where the problem comes from which makes it easier to solve :).

You're right. Using pydantic version 2.6.2 fixed that issue like a charm.

**Comment by jonathan-s** [comment]
I'm going to merge this and I've created a separate issue for the test failure.

**Pull request merged**
